language: ruby
rvm:
  - 2.2
install: bundle install
script: bundle exec rspec
notifications:
  email:
    - subashkc08@gmail.com
addons:
  code_climate:
    repo_token: fc536c5abf183ec0939ed2a8dac70d4c1476ce0a5666505cfef9000cbc43ce82
after_success:
  - bundle exec codeclimate-test-reporter